import type { Metadata } from "next";
import { Inter, IBM_Plex_Mono } from "next/font/google";

import {
    ClerkProvider
} from '@clerk/nextjs'
import { dark } from '@clerk/themes';

import { ThemeProvider } from '../components/theme-provider';
import Header from '../components/header';

import "./globals.css";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
    variable: "--font-plex-mono",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                theme: dark
            }}
        >
            <html lang="en" suppressHydrationWarning>
                <body className={`${inter.variable} ${plexMono.variable} antialiased`} >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Header />
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
